module:
    revision: 1
    group: 'html'
    edit_template: '@module/html/edit.html.twig'
    render_template: '@module/html/render.html.twig'
    module_options:
        label_format: 'modules.html.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'codeContainerId'

            code:
                type: 'html'
                type_options:
                    attr:
                        data-edit-content-input: 'code'